name: Update Conferences

on:
  workflow_dispatch:  # Allow manual trigger
  pull_request:
    paths:
      - 'src/data/conferences.yml'

jobs:
  update-conferences:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests
    
    - name: Update conferences
      run: python .github/scripts/update_conferences.py
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 'chore: update conference data from ccfddl'
        title: 'Update conference data from ccfddl'
        body: |
          This PR updates the conference data from the ccfddl repository.
          
          Auto-generated by GitHub Actions.
        branch: update-conferences
        delete-branch: true
        base: main 